allowBuilds:
  esbuild: true
  lightningcss: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.27'
  - '@better-auth/drizzle-adapter@1.6.27'
  - '@better-auth/kysely-adapter@1.6.27'
  - '@better-auth/memory-adapter@1.6.27'
  - '@better-auth/mongo-adapter@1.6.27'
  - '@better-auth/prisma-adapter@1.6.27'
  - '@better-auth/telemetry@1.6.27'
  - '@biomejs/biome@2.5.8'
  - '@biomejs/cli-darwin-arm64@2.5.8'
  - '@biomejs/cli-darwin-x64@2.5.8'
  - '@biomejs/cli-linux-arm64-musl@2.5.8'
  - '@biomejs/cli-linux-arm64@2.5.8'
  - '@biomejs/cli-linux-x64-musl@2.5.8'
  - '@biomejs/cli-linux-x64@2.5.8'
  - '@biomejs/cli-win32-arm64@2.5.8'
  - '@biomejs/cli-win32-x64@2.5.8'
  - '@tanstack/devtools-ui@0.7.0'
  - '@tanstack/devtools@0.14.0'
  - '@tanstack/form-core@1.33.5'
  - '@tanstack/react-devtools@0.10.10'
  - '@tanstack/react-form@1.33.5'
  - better-auth@1.6.27
